name: Change version (latest)

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Extract version from tag
        run: |
          tag=${GITHUB_REF#refs/*/}
          version=${tag:1}
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Test version
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}

      - name: init git repository
        run: |
          git config user.name 'Sergei Khadanovich'
          git config user.email 'khadanovich.sergey@gmail.com'

      - name: Fork new branch
        run: |
          git checkout -b versions/up/${{ env.VERSION }}
          git push origin versions/up/${{ env.VERSION }}

      - name: Change project version
        run: |
          mvn versions:set -DnewVersion=${{ env.VERSION }}
          mvn versions:commit

      - name: Commit changes
        run: git commit -am 'Version up'

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Up version to ${{ env.VERSION }}
          branch: versions/up/${{ env.VERSION }}
          delete-branch: true
          base: main
